# Generated by Django 3.2.6 on 2021-09-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0004_auto_20210923_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpapers',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
