# Generated by Django 3.2.6 on 2021-09-27 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallpapers', '0005_alter_wallpapers_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpapers',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
