# Generated by Django 3.2.6 on 2021-10-03 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallpapers', '0006_wallpapers_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpapers',
            name='likes',
            field=models.ManyToManyField(related_name='wall', to=settings.AUTH_USER_MODEL),
        ),
    ]
